# Generated by Django 5.1.6 on 2025-03-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('Wo', 'Women'), ('Me', 'Men'), ('Ki', 'Kids'), ('Pro', 'Prova'), ('Ja', 'Jackets')], max_length=200)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
