# Generated by Django 5.1.6 on 2025-03-06 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(choices=[('dodoma', 'dodoma'), ('mbeya', 'mbeya'), ('rukwa', 'rukwa'), ('arusha', 'arusha'), ('kilimanjaro', 'kilimanjaro'), ('dar es salaam', 'dar es saalam'), ('singida', 'singida'), ('songea', 'songea'), ('iringa', 'iringa'), ('morogoro', 'morogoro'), ('mwanza', 'mwanza'), ('kagera', 'kagera'), ('bukoba', 'bukoba'), ('songwe', 'songwe')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
