# Generated by Django 5.1.6 on 2025-03-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('dodoma', 'dodoma'), ('mbeya', 'mbeya'), ('rukwa', 'rukwa'), ('arusha', 'arusha'), ('kilimanjaro', 'kilimanjaro'), ('dar es salaam', 'dar es saalam'), ('singida', 'singida'), ('songea', 'songea'), ('iringa', 'iringa'), ('morogoro', 'morogoro'), ('mwanza', 'mwanza'), ('kagera', 'kagera'), ('bukoba', 'bukoba'), ('songwe', 'songwe'), ('tabora', 'tabora'), ('njombe', 'njombe'), ('songwe', 'songwe'), ('kagera', 'kagera'), ('moshi', 'moshi'), ('shinyanga', 'shinyanga'), ('tanga', 'tanga'), ('musoma', 'musuma'), ('geita', 'geita')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Wo', 'Women'), ('Me', 'Men'), ('Ki', 'Kids'), ('El', 'Electonics'), ('Cel', 'Celphone')], max_length=200),
        ),
    ]
